name = "Agnes"
license = "GPL-3.0"
licenselink = "https://github.com/dchucks/agnes-hugo-theme/blob/main/LICENSE"
description = 'Agnes is a landing page Hugo theme ported from the free HTML template designed by Cruip, a marketplace of Tailwind CSS templates. The design is lovely and features an intro screenshot preview, a product/service list, and a three-tier pricing table.'

# The home page of the theme, where the source can be found.
homepage = "https://github.com/dchucks/agnes-hugo-theme"

# If you have a running demo of the theme.
demosite = "https://agnes-hugo-sample-site.netlify.app/"

tags = ["Landing", "Light", "Company", "Minimal"]
features = ["Single Page Website", "Blazing Fast", "Easy to deploy and configure"]

# If the theme has a single author
[author]
    name = "Debashish Chakrabarty"
    homepage = "https://www.debashish.com"
